// Project Images Data
// This file contains image mappings for project galleries

export const projectImageMap: Record<number, string[]> = {
  1: [
    "/disbursement/login.png",
    "/disbursement/1.png",
    "/disbursement/2.png",
    "/disbursement/3.png",
    "/disbursement/4.png",
    "/disbursement/5.png",
    "/disbursement/6.png",
    "/disbursement/7.png",
    "/disbursement/8.png",
    "/disbursement/9.png",
    "/disbursement/10.png",
  ],
  2: [
    "/uonepay/cover.png",
    "/uonepay/1.png",
    "/uonepay/2.png",
    "/uonepay/3.png",
    "/uonepay/4.png",
    "/uonepay/5.png",
  ],
  4: [
    "/travel/1.png",
    "/travel/2.png",
    "/travel/3.png",
    "/travel/4.png",
    "/travel/6.png",
    "/travel/7.png",
    "/travel/8.png",
  ],
  5: [
    "/ifortepay/cover.png",
    "/ifortepay/1.png",
    "/ifortepay/2.png",
    "/ifortepay/3.png",
    "/ifortepay/4.png",
    "/ifortepay/5.png",
    "/ifortepay/6.png",
    "/ifortepay/7.png",
    "/ifortepay/8.png",
    "/ifortepay/9.png",
  ],
  6: [
    "/globemen/cover.png",
    "/globemen/1.png",
    "/globemen/2.png",
    "/globemen/3.png",
  ],
  7: [
    "/kostfinenace/cover.png",
    "/kostfinenace/1.png",
    "/kostfinenace/2.png",
    "/kostfinenace/3.png",
    "/kostfinenace/4.png",
    "/kostfinenace/5.png",
    "/kostfinenace/6.png",
  ],
  18: [
    "/bendaku/cover.png",
    "/bendaku/login.png",
    "/bendaku/1.png",
    "/bendaku/2.png",
    "/bendaku/3.png",
    "/bendaku/4.png",
    "/bendaku/5.png",
    "/bendaku/6.png",
    "/bendaku/7.png",
    "/bendaku/8.png",
    "/bendaku/9.png",
  ],
  19: [
    "/bendaku_backend/1.png",
    "/bendaku_backend/2.png",
    "/bendaku_backend/3.png",
    "/bendaku_backend/4.png",
    "/bendaku_backend/5.png",
    "/bendaku_backend/6.png",
  ],
  23: [
    "/ifortepay/cover.png",
    "/ifortepay/1.png",
    "/ifortepay/2.png",
    "/ifortepay/3.png",
    "/ifortepay/4.png",
    "/ifortepay/5.png",
    "/ifortepay/6.png",
    "/ifortepay/7.png",
    "/ifortepay/8.png",
    "/ifortepay/9.png",
  ],
  24: [
    "/ifortepay/cover.png",
    "/ifortepay/1.png",
    "/ifortepay/2.png",
    "/ifortepay/3.png",
    "/ifortepay/4.png",
    "/ifortepay/5.png",
    "/ifortepay/6.png",
    "/ifortepay/7.png",
    "/ifortepay/8.png",
    "/ifortepay/9.png",
  ],
  25: [
    "/forgeui/1.png",
    "/forgeui/2.png",
    "/forgeui/3.png",
    "/forgeui/4.png",
  ],
  26: [
    "/local-market/1.png",
    "/local-market/2.png",
    "/local-market/3.png",
  ],
  27: [
    "/pg-disburse/1.png",
    "/pg-disburse/2.png",
    "/pg-disburse/3.png",
    "/pg-disburse/4.png",
    "/pg-disburse/5.png",
  ],
  28: [
    "/qa-automation/1.png",
    "/qa-automation/2.png",
  ],
  29: [
    "/workblom/1.png",
  ],
};

// Helper function to get project images
export function getProjectImages(projectId: number, mainImage: string): string[] {
  return projectImageMap[projectId] || [mainImage];
}

